version: 2.1

jobs:
  cypress:
    docker:
      - image: cypress/included:13.16.1 # Using Cypress Docker image
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install # Install dependencies
      - run:
          name: Install Cypress Binary
          command: |
            npx cypress install # Install the Cypress binary explicitly
      - run:
          name: Run Cypress Tests
          command: |
            npx cypress run # Run Cypress tests
      - save_cache:
          paths:
            - ~/.cache/Cypress # Cache Cypress binary
            - ./node_modules # Cache node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }} # Cache key using package files

workflows:
  version: 2
  test:
    jobs:
      - cypress # Reference the job name directly in the workflow
